name: black-linter

on:
  push:
    branches: [main]
    paths:
      - solution/**
      - lcs/**
      - lcp/**
      - lcof2/**
      - lcof/**
      - lcci/**
      - basic/**
      - requirements.txt
      - .github/workflows/black-lint.yml
  pull_request:
    paths:
      - solution/**
      - lcs/**
      - lcp/**
      - lcof2/**
      - lcof/**
      - lcci/**
      - basic/**
      - requirements.txt
      - .github/workflows/black-lint.yml

concurrency:
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install black
        run: python -m pip install -r requirements.txt
      - name: Check black
        run: python -m black -S --check .
