name: clang-format-linter

on:
  push:
    branches: [main]
    paths:
      - solution/**
      - lcs/**
      - lcp/**
      - lcof2/**
      - lcof/**
      - lcci/**
      - basic/**
      - .github/workflows/clang-format-lint.yml
  pull_request:
    paths:
      - solution/**
      - lcs/**
      - lcp/**
      - lcof2/**
      - lcof/**
      - lcci/**
      - basic/**
      - .github/workflows/clang-format-lint.yml

concurrency:
  group: ${{github.workflow}} - ${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: '.'
          extensions: 'c,cpp,java'
          clangFormatVersion: 16